version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm start
  mongo:
    image: mongo
  # test:
  #   build: .
  #   volumes:
  #     - ./:/app
  #   command: npm test
